#!/bin/sh

DEFAULT_NTP_POOLS="0.pool.ntp.org,1.pool.ntp.org,2.pool.ntp.org,3.pool.ntp.org"
DEFAULT_ALLOWED_NETWORKS="192.168.0.0/16,172.16.0.0/12,10.0.0.0/8"
DEFAULT_LOCAL_OPTION="local stratum 10"
DEFAULT_NTP_PORT="123"
CHRONY_CONFIG_PATH="/etc/chrony/chrony.conf"
CHRONY_USER="chrony"

# Set NTP Pools
if [ -z "${NTP_POOLS}" ]; then
  NTP_POOLS="${DEFAULT_NTP_POOLS}"
fi
if [ "${NTP_POOLS}" = "NONE" ]; then
  NTP_POOLS=""
fi

# Set Local Option
if [ -z "${LOCAL_OPTION}" ]; then
  LOCAL_OPTION="${DEFAULT_LOCAL_OPTION}"
fi
if [ "${LOCAL_OPTION}" = "NONE" ]; then
  LOCAL_OPTION=""
fi

# Set Port
if [ -z "${NTP_PORT}" ]; then
  NTP_PORT="${DEFAULT_NTP_PORT}"
fi

# Set Allowed Networks
if [ -z "${ALLOWED_NETWORKS}" ]; then
  ALLOWED_NETWORKS="${DEFAULT_ALLOWED_NETWORKS}"
fi

# Set log level
# chrony log levels: 0 (informational), 1 (warning), 2 (non-fatal error) and 3 (fatal error)
if [ -z "${LOG_LEVEL}" ]; then
  LOG_LEVEL=0
else
  if [ "${LOG_LEVEL}" -gt 3 ]; then
    LOG_LEVEL=0
  fi
fi

# Generate config
{
  echo "# https://chrony.tuxfamily.org/doc/4.1/chrony.conf.html"
  echo ""
  echo "# pool of time servers, use at least 4"
  
  IFS=","
  for N in $NTP_POOLS; do
    echo "pool "${N//\"}" iburst maxsources 5"
  done


  echo ""
  echo "# Allow clients from local sources"
  for N in $ALLOWED_NETWORKS; do
    echo "allow "${N//\"}""
  done

  echo ""
  echo "# Set the PID file"
  echo "pidfile /run/chrony/chronyd.pid"
  echo ""
  echo "# Set the chronyd port"
  echo "port ${NTP_PORT}"
  echo ""
  echo "# Record the rate at which the system clock gains/losses time."
  echo "driftfile /var/lib/chrony/chrony.drift"
  echo "${LOCAL_OPTION}"
  echo ""
  echo "# Allow the system clock to be stepped in the first three updates"
  echo "# if its offset is larger than 1 second."
  echo "makestep 0.1 3"
  #echo "commandkey 1"
  #echo "manual"
  #echo "keyfile /etc/chrony.keys"
  echo ""
  echo "## Logging"
  echo "logdir /run/chrony/logs"
  echo "log measurements statistics tracking"
} > ${CHRONY_CONFIG_PATH}

# Run the Chrony daemon
exec /usr/sbin/chronyd -u ${CHRONY_USER} -d -x -U -f ${CHRONY_CONFIG_PATH} -L ${LOG_LEVEL}