#!/bin/sh

DEFAULT_NTP_POOLS="time.cloudflare.com,pool.ntp.org"
DEFAULT_ALLOWED_NETWORKS="192.168.0.0/16,172.16.0.0/12,10.0.0.0/8"
CHRONY_CONFIG_PATH="/etc/chrony/chrony.conf"
CHRONY_USER="chrony"

# Set NTP Pools
if [ -z "${NTP_POOLS}" ]; then
  NTP_POOLS="${DEFAULT_NTP_POOLS}"
fi

# Set Allowed Networks
if [ -z "${ALLOWED_NETWORKS}" ]; then
  ALLOWED_NETWORKS="${DEFAULT_ALLOWED_NETWORKS}"
fi

# Set log level
# chrony log levels: 0 (informational), 1 (warning), 2 (non-fatal error) and 3 (fatal error)
if [ -z "${LOG_LEVEL}" ]; then
  LOG_LEVEL=0
else
  if [ "${LOG_LEVEL}" -gt 3 ]; then
    LOG_LEVEL=0
  fi
fi

# Generate config
{
  echo "# https://chrony.tuxfamily.org/doc/4.1/chrony.conf.html"
  echo ""
  echo "# pool of time servers, use 3"
  
  IFS=","
  for N in $NTP_POOLS; do
    echo "pool "${N//\"}" iburst maxsources 3"
  done


  echo ""
  echo "# Allow clients from local sources"
  for N in $ALLOWED_NETWORKS; do
    echo "allow "${N//\"}""
  done

  echo ""
  echo "# Set the PID file"
  echo "pidfile /run/chrony/chronyd.pid"
  echo ""
  echo "# Record the rate at which the system clock gains/losses time."
  echo "driftfile /var/lib/chrony/chrony.drift"
  echo "local stratum 2"
  echo ""
  echo "# Allow the system clock to be stepped in the first three updates"
  echo "# if its offset is larger than 1 second."
  echo "makestep 0.1 3"
  #echo "commandkey 1"
  #echo "manual"
  #echo "keyfile /etc/chrony.keys"
  echo ""
  echo "## Logging"
  echo "logdir /run/chrony/logs"
  echo "log measurements statistics tracking"
} > ${CHRONY_CONFIG_PATH}

# Run the Chrony daemon
exec /usr/sbin/chronyd -u ${CHRONY_USER} -d -x -U -f ${CHRONY_CONFIG_PATH} -L ${LOG_LEVEL}